# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 742)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("border-image: url(:/newPrefix/image/background.png);\n"
"font: 16pt \"Arial\";")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 701))
        self.horizontalLayoutWidget.setAutoFillBackground(False)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("font: 25 10pt \"微软雅黑 Light\";")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_url = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_url.setGeometry(QtCore.QRect(240, 40, 419, 61))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(690, 30, 321, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_run = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_run.setStyleSheet("font: 25 16pt \"微软雅黑 Light\";")
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_4.addWidget(self.pushButton_run)
        self.pushButton_in = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_in.setAutoFillBackground(False)
        self.pushButton_in.setStyleSheet("font: 25 16pt \"微软雅黑 Light\";")
        self.pushButton_in.setObjectName("pushButton_in")
        self.horizontalLayout_4.addWidget(self.pushButton_in)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(160, 50, 71, 31))
        self.label.setStyleSheet("font: 25 16pt \"微软雅黑 Light\";")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 110, 1281, 531))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_init = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_init.setAutoFillBackground(False)
        self.label_init.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 25 16pt \"微软雅黑 Light\";")
        self.label_init.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_init.setMidLineWidth(0)
        self.label_init.setObjectName("label_init")
        self.horizontalLayout_5.addWidget(self.label_init)
        self.label_out = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_out.setMouseTracking(True)
        self.label_out.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_out.setAutoFillBackground(False)
        self.label_out.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 16pt \"微软雅黑 Light\";")
        self.label_out.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_out.setTextFormat(QtCore.Qt.AutoText)
        self.label_out.setScaledContents(False)
        self.label_out.setWordWrap(False)
        self.label_out.setObjectName("label_out")
        self.horizontalLayout_5.addWidget(self.label_out)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 301, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(670, 20, 91, 41))
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 80, 1291, 561))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_para = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_para.setAutoFillBackground(False)
        self.label_para.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_para.setMidLineWidth(0)
        self.label_para.setObjectName("label_para")
        self.horizontalLayout_8.addWidget(self.label_para)
        self.label_paraImage = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_paraImage.setAutoFillBackground(False)
        self.label_paraImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_paraImage.setMidLineWidth(0)
        self.label_paraImage.setObjectName("label_paraImage")
        self.horizontalLayout_8.addWidget(self.label_paraImage)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(760, 0, 441, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_para1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_para1.setObjectName("radioButton_para1")
        self.horizontalLayout_2.addWidget(self.radioButton_para1)
        self.radioButton_para2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_para2.setObjectName("radioButton_para2")
        self.horizontalLayout_2.addWidget(self.radioButton_para2)
        self.radioButton_para3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_para3.setObjectName("radioButton_para3")
        self.horizontalLayout_2.addWidget(self.radioButton_para3)
        self.radioButton_para4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_para4.setObjectName("radioButton_para4")
        self.horizontalLayout_2.addWidget(self.radioButton_para4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.label_13.setStyleSheet("font: 25 14pt \"微软雅黑 Light\";")
        self.label_13.setObjectName("label_13")
        self.label_bugImage = QtWidgets.QLabel(self.tab_5)
        self.label_bugImage.setGeometry(QtCore.QRect(10, 70, 636, 461))
        self.label_bugImage.setAutoFillBackground(False)
        self.label_bugImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_bugImage.setMidLineWidth(0)
        self.label_bugImage.setObjectName("label_bugImage")
        self.pushButton_bugIn = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_bugIn.setGeometry(QtCore.QRect(60, 620, 121, 31))
        self.pushButton_bugIn.setStyleSheet("font: 25 12pt \"微软雅黑 Light\";")
        self.pushButton_bugIn.setObjectName("pushButton_bugIn")
        self.pushButton_cut = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_cut.setGeometry(QtCore.QRect(290, 620, 111, 31))
        self.pushButton_cut.setMouseTracking(False)
        self.pushButton_cut.setCheckable(False)
        self.pushButton_cut.setAutoDefault(False)
        self.pushButton_cut.setDefault(False)
        self.pushButton_cut.setFlat(False)
        self.pushButton_cut.setObjectName("pushButton_cut")
        self.pushButton_bugsubmit = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_bugsubmit.setGeometry(QtCore.QRect(520, 620, 93, 28))
        self.pushButton_bugsubmit.setObjectName("pushButton_bugsubmit")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(130, 560, 151, 31))
        self.label_15.setObjectName("label_15")
        self.lineEdit_bugNumber = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_bugNumber.setGeometry(QtCore.QRect(300, 560, 151, 31))
        self.lineEdit_bugNumber.setObjectName("lineEdit_bugNumber")
        self.textEdit_advice = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_advice.setGeometry(QtCore.QRect(650, 70, 631, 271))
        self.textEdit_advice.setObjectName("textEdit_advice")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(650, 10, 481, 51))
        self.label_16.setStyleSheet("font: 25 14pt \"微软雅黑 Light\";")
        self.label_16.setObjectName("label_16")
        self.pushButton_cancel = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_cancel.setGeometry(QtCore.QRect(770, 420, 141, 41))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_advice = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_advice.setGeometry(QtCore.QRect(1020, 420, 131, 41))
        self.pushButton_advice.setObjectName("pushButton_advice")
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_run.clicked.connect(MainWindow.runModel)
        self.pushButton_in.clicked.connect(MainWindow.openImage)
        self.pushButton_bugIn.clicked.connect(MainWindow.openImage)
        self.radioButton_para1.toggled['bool'].connect(MainWindow.paraImage1)
        self.radioButton_para2.toggled['bool'].connect(MainWindow.paraImage2)
        self.radioButton_para3.toggled['bool'].connect(MainWindow.paraImage3)
        self.radioButton_para4.toggled['bool'].connect(MainWindow.paraImage4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "银行卡识别"))
        MainWindow.setStatusTip(_translate("MainWindow", "银色子弹"))
        self.pushButton_run.setStatusTip(_translate("MainWindow", "点击按钮开始识别"))
        self.pushButton_run.setText(_translate("MainWindow", "检测"))
        self.pushButton_in.setStatusTip(_translate("MainWindow", "点击按钮上传文档"))
        self.pushButton_in.setText(_translate("MainWindow", "上传"))
        self.label.setText(_translate("MainWindow", "路径："))
        self.label_init.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">原始图片</span></p></body></html>"))
        self.label_out.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">输出结果</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "功能演示"))
        self.label_4.setText(_translate("MainWindow", "模型训练指标："))
        self.label_5.setText(_translate("MainWindow", "请选择："))
        self.label_para.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:blueGreen;\">详参：</span></p></body></html>"))
        self.label_paraImage.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">参数图像</span></p></body></html>"))
        self.radioButton_para1.setStatusTip(_translate("MainWindow", "点击后显示该参数图像"))
        self.radioButton_para1.setText(_translate("MainWindow", "decay=0"))
        self.radioButton_para2.setStatusTip(_translate("MainWindow", "点击后显示该参数图像"))
        self.radioButton_para2.setText(_translate("MainWindow", "decay=lr/ep"))
        self.radioButton_para3.setStatusTip(_translate("MainWindow", "点击后显示该参数图像"))
        self.radioButton_para3.setText(_translate("MainWindow", "nn"))
        self.radioButton_para4.setStatusTip(_translate("MainWindow", "点击后显示该参数图像"))
        self.radioButton_para4.setText(_translate("MainWindow", "Lastpick"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "模型"))
        self.label_13.setText(_translate("MainWindow", "识别有误的图片："))
        self.label_bugImage.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">请上传识别有误的银行卡照片</span></p></body></html>"))
        self.pushButton_bugIn.setStatusTip(_translate("MainWindow", "上传有问题的银行卡照片"))
        self.pushButton_bugIn.setText(_translate("MainWindow", "上传"))
        self.pushButton_cut.setStatusTip(_translate("MainWindow", "当点击该button时，自动切割识别有误的数字部分"))
        self.pushButton_cut.setText(_translate("MainWindow", "切割"))
        self.pushButton_bugsubmit.setStatusTip(_translate("MainWindow", "上传至训练集，继续训练，提高模型准确度"))
        self.pushButton_bugsubmit.setText(_translate("MainWindow", "提交"))
        self.label_15.setText(_translate("MainWindow", "错误数字号码："))
        self.lineEdit_bugNumber.setStatusTip(_translate("MainWindow", "请手动输入有误的数字"))
        self.label_16.setText(_translate("MainWindow", "识别信息："))
        self.pushButton_cancel.setText(_translate("MainWindow", "取消"))
        self.pushButton_advice.setText(_translate("MainWindow", "提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "反馈交互"))

